general.import = ["./dracula.toml"]

[font]
size = 12.0

[font.bold]
family = "JetBrainsMonoNL NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL NF"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL NF"
style = "Regular"

[window]
decorations = "None"

[terminal]
shell = { program = "nu", args = [""] }
